export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_LOADED = 'GET_POSTS_LOADED';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const GET_POST_LOADING = 'GET_POST_LOADING';
export const GET_POST_LOADED = 'GET_POST_LOADED';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const GET_ABOUT_LOADING = 'GET_ABOUT_LOADING';
export const GET_ABOUT_LOADED = 'GET_ABOUT_LOADED';
export const GET_ABOUT_ERROR = 'GET_ABOUT_ERROR';
